"""Renaming password_hash to password

Revision ID: 99da7041065a
Revises: d0bb9eda164d
Create Date: 2025-02-24 22:49:01.331721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99da7041065a'
down_revision = 'd0bb9eda164d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
